apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      containers:
        - name: ingestion
          image:
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ingestion
spec:
  selector:
    app: ingestion
  ports:
    - port: 8080
      targetPort: 8080
