#name: CI Pipeline
#on:
#  push:
#    branches: ["main"]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        component: [backend, agent, dashboard]
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up Go or Node.js
#        uses: actions/setup-go@v4
#        if: matrix.component != 'dashboard'
#        with:
#          go-version: '1.20'
#      - uses: actions/setup-node@v3
#        if: matrix.component == 'dashboard'
#        with:
#          node-version: '18'
#      - name: Build ${{ matrix.component }}
#        run: |
#          cd ${{ matrix.component }}
#          if [ "${{ matrix.component }}" = "dashboard" ]; then npm install && npm run build; else go build .; fi
